import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.m`odule.css";
import { useRef, useState } from "react";
import { Sidebar, Widget } from "../components";

export default function Home() {
	const [pickUpStyle, setPickUpStyle] = useState("bg-red-600 text-white");
	const [pickUpBtnText, setPickUpBtnText] = useState("Find Bike");
	const fromLocationRef = useRef<any>();
	const handlePickUpStyle = () => {
		setPickUpBtnText("Searching");
		setPickUpStyle("bg-green-600 text-white");
		setTimeout(() => {
			setPickUpBtnText("Match");
			setPickUpStyle("bg-blue-600 text-white");
			setTimeout(() => {}, 2000);
		}, 5000);
	};

	return (
		<div className="flex flex-col justify-center items-center h-screen bg-slate-300 ">
			<Head>
				<title>Forex Backtest</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="shadow w-full flex flex-col items-center">
				<nav className="flex h-16 items-center justify-between px-3 container ">
					<p className="logo text-xl font-extrabold italic lowercase">LOGO</p>
					<div className="links flex gap-3">
						<a href="/" className="link">
							Home
						</a>
						<a href="/" className="link">
							Calculator
						</a>
						<a href="/" className="link">
							Risk Management
						</a>
						<a href="/" className="link">
							Strategies
						</a>
					</div>
				</nav>
			</div>
			<div className="bg-black w-full h-full text-gray-100 flex justify-center">
				<main className="container h-full lg:flex   py-3">
					<div className=" lg:w-52 shadow-sm">
						<Sidebar />
					</div>
					<div className=" w-full">
						<Widget />
					</div>
				</main>
			</div>

			<footer className="h-70">.....</footer>
		</div>
	);
}
